### ISSUE TITLE
Encoding issue after using ms_simplify()

### ISSUE THREAD

**Issue by philstraforelli** [ateucher/rmapshaper#67] opened 2018-01-11 23:50 UTC
See the following reprex:

``` r
library(raster)
#> Loading required package: sp
library(rmapshaper)

France_map <- getData(name = "GADM", path = "", country = "France", level = 1)
France_map$NAME_1
#> [1] "Alsace"                     "Aquitaine"                  "Auvergne"                  
#> [4] "Île-de-France"              "Basse-Normandie"            "Bourgogne"                 
#> [7] "Bretagne"                   "Centre"                     "Champagne-Ardenne"         
#> [10] "Corse"                      "Franche-Comté"              "Haute-Normandie"           
#> [13] "Languedoc-Roussillon"       "Limousin"                   "Lorraine"                  
#> [16] "Midi-Pyrénées"              "Nord-Pas-de-Calais"         "Pays de la Loire"          
#> [19] "Picardie"                   "Poitou-Charentes"           "Provence-Alpes-Côte d'Azur"
#> [22] "Rhône-Alpes"

France_map_simpl <- ms_simplify(France_map)
France_map_simpl$NAME_1
#>  [1] "Alsace"                      "Aquitaine"                  
#>  [3] "Auvergne"                    "ÃƒÅ½le-de-France"             
#>  [5] "Basse-Normandie"             "Bourgogne"                  
#>  [7] "Bretagne"                    "Centre"                     
#>  [9] "Champagne-Ardenne"           "Corse"                      
#> [11] "Franche-ComtÃƒÂ©"              "Haute-Normandie"            
#> [13] "Languedoc-Roussillon"        "Limousin"                   
#> [15] "Lorraine"                    "Midi-PyrÃƒÂ©nÃƒÂ©es"            
#> [17] "Nord-Pas-de-Calais"          "Pays de la Loire"           
#> [19] "Picardie"                    "Poitou-Charentes"           
#> [21] "Provence-Alpes-CÃƒÂ´te d'Azur" "RhÃƒÂ´ne-Alpes"
```

I can work around it, but I just thought you should be aware of this.

**Comment by ateucher** [comment] 2018-01-13 00:04
Hi @philstraforelli - thanks so much for the report and reproducible example. I will look into it.

**Comment by ateucher** [comment] 2018-01-13 04:44
I can't reproduce this on my Mac... @philstraforelli are you on Windows? 

Just so I can rule out an issue with `V8`, can you check if this returns the correct string?

```r
library(V8)
ctx <- v8()
ctx$assign("x", "Provence-Alpes-Côte d'Azur")
ctx$get("x")
```

**Comment by philstraforelli** [comment] 2018-01-13 07:27
I get `"Provence-Alpes-Côte d'Azur"`.

Here's my `sessionInfo()`:

```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmapshaper_0.3.0 raster_2.6-7     sp_1.2-6         V8_1.5          

loaded via a namespace (and not attached):
 [1] compiler_3.4.3     tools_3.4.3        curl_3.1           yaml_2.1.16        Rcpp_0.12.14       jsonvalidate_1.0.0
 [7] grid_3.4.3         knitr_1.18         geojsonlint_0.2.0  jsonlite_1.5       reprex_0.1.1       lattice_0.20-35 
```

**Comment by ateucher** [comment] 2018-01-13 22:37
Thanks again @philstraforelli. I don't have a Windows machine readily available, so I hope you don't mind being a guinea pig... Can you run the following and post the output?

```r
library(geojsonio)
gj <- geojson_json(France_map[France_map$NAME_1 == "Provence-Alpes-Côte d'Azur", ])
substr(unclass(gj), 1, 500) # Just print the first 500 characters so we can see what `"Provence-Alpes-Côte d'Azur"` has been turned into
```

**Comment by philstraforelli** [comment] 2018-01-15 16:28
See below:

```
[1] "{\n\"type\": \"FeatureCollection\",\n\"crs\": { \"type\": \"name\", \"properties\": { \"name\": \"urn:ogc:def:crs:OGC:1.3:CRS84\" } },\n\"features\": [\n{ \"type\": \"Feature\", \"id\": 21, \"properties\": { \"OBJECTID\": 21, \"ID_0\": 79, \"ISO\": \"FRA\", \"NAME_0\": \"France\", \"ID_1\": 21, \"NAME_1\": \"Provence-Alpes-Côte d'Azur\", \"HASC_1\": \"\", \"CCN_1\": null, \"CCA_1\": \"93\", \"TYPE_1\": \"Région\", \"ENGTYPE_1\": \"Region\", \"NL_NAME_1\": \"\", \"VARNAME_1\": \"\" }, \"geometry\": { \"type\": \"MultiPolygon\", \"coordinates\": [ [ [ [ 6.396804809570312, 42.99"
attr(,"type")
[1] "FeatureCollection"
attr(,"no_features")
[1] "1"
attr(,"five_feats")
[1] "MultiPolygon"
```

**Comment by philstraforelli** [comment] 2018-01-15 21:33
I've been doing some other searches on the issue and noticed [this discussion](https://github.com/tidyverse/readxl/issues/125). I'm starting to think my issue is somewhat related to this one. That is, it's more of an issue related to the machine than to the rmapshaper (or readxl) package.

**Comment by ateucher** [comment] 2018-01-15 21:48
Thanks so much @philstraforelli. I've found where the bad conversion occurs (converting `geojson` string back to an `sp` object after the simplification), and I may have a solution... I'll do a bit of testing and maybe ask you to try it out later today or tomorrow...

**Comment by ateucher** [comment] 2018-01-16 20:01
@philstraforelli I think I have it fixed in the devlopment version. Can you install it from github and try your original test again?

```r
library(devtools)
install_github("ateucher/rmapshaper")

library(raster)
library(rmapshaper)

France_map <- getData(name = "GADM", path = "", country = "France", level = 1

France_map_simpl <- ms_simplify(France_map)
France_map_simpl$NAME_1
```

**Comment by philstraforelli** [comment] 2018-01-16 20:05
Success! 

```
 [1] "Alsace"                     "Aquitaine"                  "Auvergne"                  
 [4] "Île-de-France"              "Basse-Normandie"            "Bourgogne"                 
 [7] "Bretagne"                   "Centre"                     "Champagne-Ardenne"         
[10] "Corse"                      "Franche-Comté"              "Haute-Normandie"           
[13] "Languedoc-Roussillon"       "Limousin"                   "Lorraine"                  
[16] "Midi-Pyrénées"              "Nord-Pas-de-Calais"         "Pays de la Loire"          
[19] "Picardie"                   "Poitou-Charentes"           "Provence-Alpes-Côte d'Azur"
[22] "Rhône-Alpes"  
```

**Comment by ateucher** [comment] 2018-01-16 20:25
Woot! Thanks so much for the report and helping test :)

**Closed** 2018-03-26 22:28 UTC
Labels: bug

**Comment by mgarnault** [comment] 2021-07-10 19:42
Hi, sorry to bring back old problems here but I followed your method and still have encoding issues:
The _com_ data is available on my github page in repository **Help**: [https://github.com/mgarnault/Help](url) as _comFR_help.zip_

```
library("devtools")
install_github("ateucher/rmapshaper")
library("rmapshaper")
library("sf")

com=st_read("~/comFR_help",options="ENCODING=UTF-8")
com$wikipedia[1:20]
 [1] "fr:Sabran (Gard)"                      "fr:Salettes (Drôme)"                  
 [3] "fr:Salignac (Alpes-de-Haute-Provence)" "fr:Saint-Geniez"                      
 [5] "fr:La Saulce"                          "fr:Chaudebonne"                       
 [7] "fr:Claret (Alpes-de-Haute-Provence)"   "fr:Châteauvieux (Hautes-Alpes)"       
 [9] "fr:Lussan (Gard)"                      "fr:Beaumont-du-Ventoux"               
[11] "fr:Suzette"                            "fr:Bidon (Ardèche)"                   
[13] "fr:Barret-sur-Méouge"                  "fr:Villedieu (Vaucluse)"              
[15] "fr:Malaucène"                          "fr:Montbrun-les-Bains"                
[17] "fr:Saint-Paul-Trois-Châteaux"          "fr:Bouchet (Drôme)"                   
[19] "fr:Roussieux"                          "fr:Barret-de-Lioure" 

com=ms_simplify(com,keep=0.1,keep_shapes=TRUE,sys=TRUE)
com$wikipedia[1:20]
 [1] "fr:Sabran (Gard)"                      "fr:Salettes (Dr�me)"                  
 [3] "fr:Salignac (Alpes-de-Haute-Provence)" "fr:Saint-Geniez"                      
 [5] "fr:La Saulce"                          "fr:Chaudebonne"                       
 [7] "fr:Claret (Alpes-de-Haute-Provence)"   "fr:Ch�teauvieux (Hautes-Alpes)"       
 [9] "fr:Lussan (Gard)"                      "fr:Beaumont-du-Ventoux"               
[11] "fr:Suzette"                            "fr:Bidon (Ard�che)"                   
[13] "fr:Barret-sur-M�ouge"                  "fr:Villedieu (Vaucluse)"              
[15] "fr:Malauc�ne"                          "fr:Montbrun-les-Bains"                
[17] "fr:Saint-Paul-Trois-Ch�teaux"          "fr:Bouchet (Dr�me)"                   
[19] "fr:Roussieux"                          "fr:Barret-de-Lioure"
```

Do you have an idea on how to fix that ?

**Comment by ateucher** [comment] 2021-09-24 18:26
Hi @mgarnault my apologies for the extremely late response. Is this still an issue for you?

If so, can you please give me the output of `sessionInfo()`?

Also, are you able to try with `sys=FALSE`? I have a hunch that should still work as expected.
