### ISSUE TITLE
Extreme test timings 

### ISSUE THREAD

**Issue by rsbivand** [ateucher/rmapshaper#50] opened 2016-12-12 12:28 UTC
When working with sp, rgdal and rgeos, we always run recursive dependency checks. These of course take a long time, but rmapshaper now takes far longer than any other package (rgdal clocks in at roughly 2h10m for all dependencies, of which rmapshaper is:

real	24m13.731s
user	23m59.475s
sys	0m16.866s

almost all of which is in testthat.

**Comment by ateucher** [comment] 2016-12-12 17:45
Wow. I'll check into that, thanks.

**Comment by ateucher** [comment] 2016-12-14 22:20
@rsbivand just so I'm clear - this is using the CRAN version of rmapshaper with the development version of rgdal?

**Comment by rsbivand** [comment] 2016-12-15 08:35
CRAN source versions of rmapshaper, rgdal and rgeos, development version of sp at github: edzer/sp, but with rgdal and rgeos installed linking to the development version of sp. I can try with CRAN everything on a faster Fedora 25 desktop: 

```
$ time R CMD check rmapshaper_0.1.0.tar.gz
...
Status: OK

real	17m58.770s
user	17m46.919s
sys	0m12.311s
```
almost all of which is in `Running ‘testthat.R’`

**Comment by ateucher** [comment] 2016-12-15 18:16
Thanks, that is really strange. On my Windows machine (CRAN everything), I get:

```
$ time R CMD check rmapshaper_0.1.0.tar.gz
...
Status: OK

real    1m19.974s
user    0m0.000s
sys     0m0.031s
```

I'll try on my Mac and Ubuntu machine at home in the next few days and see what I can find out.

**Comment by ateucher** [comment] 2017-01-04 18:31
Hi @rsbivand I'm afraid I can't reproduce this. I've run it on all machines I can get my hands on including several r-hub build machines (Fedora, Ubuntu, Debian) with r-release and r-devel and all of them build and check quickly, with tests running on the order of ~25s.

**Comment by ateucher** [comment] 2017-01-05 19:07
Closing for now unless it come up again.

**Closed by ateucher** 2017-01-05 19:07 UTC
