### ISSUE TITLE
What about sf?

### ISSUE THREAD

**Issue by rsbivand** [ateucher/rmapshaper#51] opened 2016-12-12 12:31 UTC
What about interfacing [sf?](https://cran.r-project.org/web/packages/sf/index.html)

**Comment by ateucher** [comment] 2016-12-12 17:47
Definitely in the plan. I am working on getting sf support into [geojsonio](https://github.com/ropensci/geojsonio/pull/95) which will perform the translation to geojson (required to pass the object into the mapshaper V8 context).

**Comment by ateucher** [comment] 2017-01-05 19:06
Duplicate of #47

**Closed by ateucher** 2017-01-05 19:06 UTC
