### ISSUE TITLE
Error in context_eval(join(src), private$context)

### ISSUE THREAD

**Issue by KerenRaiter** [ateucher/rmapshaper#86] opened 2019-05-16 15:26 UTC
Hi,
I hope that this the right forum for seeking help with errors:

I ran: >landuse_simple = ms_simplify(landuse, keep= 0.3, keep_shapes=TRUE)
Where landuse is a SpatialPolygonsDataFrame (quite heavy)

and received the following error:

Error in context_eval(join(src), private$context) : 
  Error in V8 context: UserError: Unable to parse JSON
    at new UserError (<anonymous>:1:534603)
    at internal.stop (<anonymous>:1:535580)
    at stop (<anonymous>:1:534534)
    at Object.internal.importJSON (<anonymous>:1:773025)
    at Object.internal.importContent (<anonymous>:1:773509)
    at Object.api.importFile (<anonymous>:1:777005)
    at Object.api.importFiles (<anonymous>:1:775751)
    at Object.api.runCommand (<anonymous>:1:848574)
    at nextCommand (<anonymous>:1:898563)
    at <anonymous>:1:899374

Any advice on what I can do to resolve this?

**Comment by ateucher** [comment] 2019-05-16 17:26
Hi @KerenRaiter - a few questions to help me narrow down the issue:

- Can you please provide the output of your `sessionInfo()`? 
- Have you had success using `ms_simplify` on other (smaller) data sets? 
- Does the error occur immediately, or after some time chugging away?

**Comment by KerenRaiter** [comment] 2019-05-20 08:23
Hi Andy,

 

Thanks for looking into this.

I have gone  reproduce the error now, but got a different error: Error in x[[1]] : subscript out of bounds. I got this same error last time, but then experimented with a few things and then started getting the above error.

1.	Can you please provide the output of your sessionInfo()?

I have pasted the session info below. It is now a new session, but the main details should be the same.

2.	Have you had success using ms_simplify on other (smaller) data sets?

Yes, I have just tried to do a smaller dataset and it worked.

3.	Does the error occur immediately, or after some time chugging away?

After some time chugging away.

 

Regards,

Keren

 

> sessionInfo()

R version 3.5.3 (2019-03-11)

Platform: x86_64-w64-mingw32/x64 (64-bit)

Running under: Windows Server >= 2012 x64 (build 9200)

 

Matrix products: default

 

locale:

[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252

[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

 

attached base packages:

[1] grid      parallel  stats     graphics  grDevices utils     datasets  methods   base     

 

other attached packages:

[1] rmapshaper_0.4.1    OpenStreetMap_0.3.3 ggmap_3.0.0         knitr_1.22          installr_0.21.0     rasterVis_0.45     

 [7] latticeExtra_0.6-28 RColorBrewer_1.1-2  lattice_0.20-38     gridExtra_2.3       rgeos_0.4-2         magrittr_1.5       

[13] foreign_0.8-71      scales_1.0.0        biomod2_3.3-7.1     reshape_0.8.8       kernlab_0.9-27      rpart_4.1-13       

[19] randomForest_4.6-14 RSNNS_0.4-11        Rcpp_1.0.0          rJava_0.9-10        earth_4.7.0         plotmo_3.5.2       

[25] TeachingDemos_2.10  plotrix_3.7-4       glmnet_2.0-16       foreach_1.4.4       Matrix_1.2-15       mgcv_1.8-27        

[31] nlme_3.1-137        mda_0.4-10          class_7.3-15        tree_1.0-39         gbm_2.1.5           dismo_1.1-4        

[37] mailR_0.4.1         xlsx_0.6.1          beepr_1.3           png_0.1-7           forcats_0.4.0       stringr_1.4.0      

[43] dplyr_0.8.0.1       purrr_0.3.1         readr_1.3.1         tidyr_0.8.3         tibble_2.0.1        ggplot2_3.1.0      

[49] tidyverse_1.2.1     rgdal_1.4-2         usdm_1.1-18         raster_2.8-19       sdm_1.0-67          sp_1.3-1           

 

loaded via a namespace (and not attached):

[1] colorspace_1.4-0      rjson_0.2.20          httpcode_0.2.0        rstudioapi_0.9.0      hexbin_1.27.2        

 [6] audio_0.1-5.1         lubridate_1.7.4       xml2_1.2.0            codetools_0.2-16      splines_3.5.3        

[11] R.methodsS3_1.7.1     geojsonlint_0.3.0     jsonlite_1.6          pROC_1.14.0           broom_0.5.1          

[16] R.oo_1.22.0           compiler_3.5.3        httr_1.4.0            backports_1.1.3       assertthat_0.2.1     

[21] lazyeval_0.2.1        cli_1.1.0             tools_3.5.3           gtable_0.2.0          glue_1.3.0           

[26] geojson_0.3.2         V8_2.2                PresenceAbsence_1.1.9 cellranger_1.1.0      crul_0.7.4           

[31] iterators_1.0.10      xfun_0.5              xlsxjars_0.6.1        rvest_0.3.2           jqr_1.1.0            

[36] MASS_7.3-51.1         zoo_1.8-4             hms_0.4.2             curl_3.3              jsonvalidate_1.0.0   

[41] stringi_1.3.1         maptools_0.9-5        e1071_1.7-0.1         RgoogleMaps_1.4.3     rlang_0.3.1          

[46] pkgconfig_2.0.2       bitops_1.0-6          sf_0.7-3              tidyselect_0.2.5      plyr_1.8.4           

[51] R6_2.4.0              geojsonio_0.7.0       generics_0.0.2        DBI_1.0.0             pillar_1.3.1         

[56] haven_2.1.0           withr_2.1.2           units_0.6-2           survival_2.43-3       abind_1.4-5          

[61] nnet_7.3-12           modelr_0.1.4          crayon_1.3.4          jpeg_0.1-8            readxl_1.3.0         

[66] classInt_0.3-1        R.utils_2.8.0         munsell_0.5.0         viridisLite_0.3.0    

>

**Comment by ateucher** [comment] 2019-05-20 23:21
Thanks @KerenRaiter - is there any way you can share the file with me? Otherwise it's difficult for me to fix this without being able to reproduce the error.

**Comment by KerenRaiter** [comment] 2019-05-21 06:41
Hi Andy,

Sure - just please don't use it for anything else without discussing with
me. I've shared the file with rmapshaper@noreply.github.com, if you'd like
to give me a different email address to give access to, please let me know.
 landuse_b.rds
<https://drive.google.com/a/mail.huji.ac.il/file/d/1WTEnm_EsUCBhomMaF9dt7iV0s1u_fEyA/view?usp=drive_web>

# i load it into R like this:
landuse_b = readRDS("landuse_b.rds")

# the line that isn't working:
landuse_simple = rmapshaper::ms_simplify(landuse_b, keep = 0.2, keep_shapes
= TRUE)

Thanks!
Keren

Dr. Keren Raiter
Postdoctoral Research Fellow

Risk Management Ecology Lab

Department of Ecology, Evolution and Behavior
Hebrew University of Jerusalem
ResearcherID: H-3767-2017 <http://www.researcherid.com/rid/H-3767-2017>

**Comment by KerenRaiter** [comment] 2019-05-21 07:51
Hi again Andy,

I've just tried again - with the larger dataset (I have a country-wide
dataset, but sent you a somewhat smaller dataset earlier that is clipped to
a study region).
R crashed and I got this window (second screenshot is the problem details
scrolled down):
[image: image.png]
[image: image.png]
Here is the dataset i was using this time:
 landuse.unsimplified.rds
<https://drive.google.com/a/mail.huji.ac.il/file/d/16inVrAchSxeXcNGiuS9Izfo5K1SNxIY0/view?usp=drive_web>

Thanks!

Keren

Dr. Keren Raiter
Postdoctoral Research Fellow

Risk Management Ecology Lab

Department of Ecology, Evolution and Behavior
Hebrew University of Jerusalem
ResearcherID: H-3767-2017 <http://www.researcherid.com/rid/H-3767-2017>

**Comment by KerenRaiter** [comment] 2019-05-21 08:05
Hi once again Andy,

Sorry for bombarding you with emails,
I tried once more; R crashed again, but I managed to get the console
output: below in red.

Regards,
Keren


<--- Last few GCs --->

[11384:000000001F8C6600]       94 ms: Scavenge 3.5 (7.0) -> 2.6 (7.5) MB,
0.3 / 0.0 ms  allocation failure
[11384:000000001F8C6600]   145585 ms: Scavenge 4.2 (7.5) -> 4.0 (8.0) MB,
0.9 / 0.0 ms  allocation failure
[11384:000000001F8C6600]   145613 ms: Scavenge 5.5 (8.5) -> 5.3 (9.0) MB,
2.0 / 0.0 ms  allocation failure
[11384:000000001F8C6600]   511192

 ms: Scavenge 8.6 (10.7) -> 8.3 (12.2) MB, 1.4 / 0.0 ms  allocation failure


<--- JS stacktrace --->

#
# Fatal process OOM in NewArray
#


==== C stack trace ===============================

ZN2v88internal17NativesCollectionILNS0_10NativeTypeE2EE16GetScriptsSourceEv
[0x0x6100deed+33277]
ZN2v815ValueSerializer8Delegate22GetSharedArrayBufferIdEPNS_7IsolateENS_5LocalINS_17SharedArrayBufferEEE
[0x0x60a6ab0d+11341]
ZN2v815ValueSerializer8Delegate22GetSharedArrayBufferIdEPNS_7IsolateENS_5LocalINS_17SharedArrayBufferEEE
[0x0x60a6ad0f+11855]
ZN2v88internal23FatalProcessOutOfMemoryEPKc [0x0x60a6addb+11]
ZN2v88internal7MemMoveEPvPKvy [0x0x6116a1cd+18141]
ZN2v88internal13ScannerStream3ForEPNS_14ScriptCompiler20ExternalSourceStreamENS2_14StreamedSource8EncodingEPNS0_16RuntimeCallStatsE
[0x0x60c82b80+10272]
ZN2v88internal13ScannerStream3ForEPNS_14ScriptCompiler20ExternalSourceStreamENS2_14StreamedSource8EncodingEPNS0_16RuntimeCallStatsE
[0x0x60c83943+13795]
ZN2v88internal13ScannerStream3ForEPNS_14ScriptCompiler20ExternalSourceStreamENS2_14StreamedSource8EncodingEPNS0_16RuntimeCallStatsE
[0x0x60c85c58+22776]
ZN2v88internal13ScannerStream3ForEPNS_14ScriptCompiler20ExternalSourceStreamENS2_14StreamedSource8EncodingEPNS0_16RuntimeCallStatsE
[0x0x60c8670d+25517]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610dbbd8+45944]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610f12d3+133747]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610e98d9+102521]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610e58b5+86101]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610e6e60+91648]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610ef373+125715]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610ec18a+112938]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610db8b7+45143]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610f12d3+133747]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610e98d9+102521]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610e58b5+86101]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610e6e60+91648]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610ef373+125715]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610ec18a+112938]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610f093b+131291]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610f4dd3+148851]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610dbe95+46645]
ZN2v88internal10DictionaryINS0_22SeededNumberDictionaryENS0_27SeededNumberDictionaryShapeEE5AtPutENS0_6HandleIS2_EEjNS5_INS0_6ObjectEEENS0_15PropertyDetailsE
[0x0x610e1159+67833]
ZN2v88internal6Parser14DoParseProgramEPNS0_9ParseInfoE [0x0x60c73f00+720]
ZN2v88internal6Parser12ParseProgramEPNS0_7IsolateEPNS0_9ParseInfoE
[0x0x60c74446+486]
ZN2v88internal7parsing12ParseProgramEPNS0_9ParseInfoEPNS0_7IsolateE
[0x0x60c74d76+390]
ZN2v88internal14CompilationJob10PrepareJobEv [0x0x60b0cbdb+2763]
ZN2v88internal8Compiler30GetSharedFunctionInfoForScriptENS0_6HandleINS0_6StringEEENS2_INS0_6ObjectEEEiiNS_19ScriptOriginOptionsES6_NS2_INS0_7ContextEEEPNS_9ExtensionEPPNS0_10ScriptDataENS_14ScriptCompiler14CompileOptionsENS0_11NativesFlagE
[0x0x60b0dc13+931]
ZN2v814ScriptCompiler22CompileUnboundInternalEPNS_7IsolateEPNS0_6SourceENS0_14CompileOptionsE
[0x0x60a8727e+926]
ZN2v814ScriptCompiler7CompileENS_5LocalINS_7ContextEEEPNS0_6SourceENS0_14CompileOptionsE
[0x0x60a879db+43]
ZN2v86Script7CompileENS_5LocalINS_7ContextEEENS1_INS_6StringEEEPNS_12ScriptOriginE
[0x0x60a87b42+194]
V8_make_context [0x0x60a6345e+1182]
Z12context_evalN4Rcpp6StringENS_4XPtrIN2v810PersistentINS2_7ContextENS2_27NonCopyablePersistentTraitsIS4_EEEENS_15PreserveStorageEXadL_ZNS_25standard_delete_finalizerIS7_EEvPT_EELb0EEE
[0x0x60a63b07+343]
V8_context_eval [0x0x60a625b7+151]
Rf_NewFrameConfirm [0x0x6c7ab644+34708]
R_initAssignSymbols [0x0x6c7f37ac+42812]
Rf_eval [0x0x6c7ffc71+817]
R_cmpfun1 [0x0x6c801284+1220]
Rf_applyClosure [0x0x6c802312+370]
R_initAssignSymbols [0x0x6c7f524a+49626]
Rf_eval [0x0x6c7ffc71+817]
Rf_eval [0x0x6c80030c+2508]
R_initAssignSymbols [0x0x6c7fde5c+85484]
Rf_eval [0x0x6c7ffc71+817]
R_cmpfun1 [0x0x6c801284+1220]
Rf_applyClosure [0x0x6c802312+370]
R_initAssignSymbols [0x0x6c7f524a+49626]
Rf_eval [0x0x6c7ffc71+817]
R_cmpfun1 [0x0x6c801284+1220]
Rf_applyClosure [0x0x6c802312+370]
R_initAssignSymbols [0x0x6c7f524a+49626]
Rf_eval [0x0x6c7ffc71+817]
R_cmpfun1 [0x0x6c801284+1220]
Rf_applyClosure [0x0x6c802312+370]
R_initAssignSymbols [0x0x6c7f524a+49626]
Rf_eval [0x0x6c7ffc71+817]
R_cmpfun1 [0x0x6c801284+1220]
Rf_applyClosure [0x0x6c802312+370]

Dr. Keren Raiter
Postdoctoral Research Fellow

Risk Management Ecology Lab

Department of Ecology, Evolution and Behavior
Hebrew University of Jerusalem
ResearcherID: H-3767-2017 <http://www.researcherid.com/rid/H-3767-2017>

**Comment by ateucher** [comment] 2019-05-21 16:57
Thanks @KerenRaiter - can you please share it with andy.teucher@gmail.com?

**Comment by KerenRaiter** [comment] 2019-05-21 17:13
Hi Andy I’ve shared it just now, did you get the link? thanks Keren

‫ב-21 במאי 2019, בשעה 19:57, ‏‏Andy Teucher ‏<notifications@github.com> כתב/ה:‬

**Comment by ateucher** [comment] 2019-05-22 17:39
I can reproduce the error - it is due to the underlying [v8](https://cran.r-project.org/package=V8) javascript session running out of memory. Please see #83 for a solution.

Incidentally, the file you sent has many topological issues (unclosed polygons, self-intersecting lines, etc). See `rgeos::gIsValid(x, byid = TRUE, reason = TRUE)`.

I'm going to close this and track the memory issue in #83.

**Closed by ateucher** 2019-05-22 17:39 UTC
